## <font color=red>  Exercise \#1: Python review </font>

## Total Points  : 50  
### <font color=Blue> Due: Tuesday 02/07/2023 11:59 PM </font>
#### Objective : Assess your ability to use Numpy Python package to  Create, index, and manipulate Arrays and Lists 

##### Skills needed:  In this homework assignment, you'll be using the concepts you've learned to
1. Edit and run  Jupyter notebooks
2. Write Python code using Numpy package to :
    * import the numpy package
    * Create arrays
    * Slice arrays 
    * Create boolean masks using some condition to index array elements

------
### <font color=darkorange> Type your name in the cell below: </font>

# Mehnaz Afrose

-----

## Requirements & Submission:
1. Use this notebook as a template for your answers. Then rename it as ` your first name`-`Last name-Ex1.ipynb`. 
2. Submit on WTClass (“Resources >> Tests, exercises and Quizzes >> Exercise#1 
3. Each task's answer must be given in the cells after the task description
4. Answers and explanations must be properly formatted in the appropriate Cell type
5. You can add as many cells as you needed
6. You should submit final ***clean version*** of your notebook, i.e. remove any experimenting cells

---------

## Task  <font color=darkred>:  [50 points]</font>
#### Write python code to:
1. Create 2D-array (identified by variable name `X`) with dimensions of 8x6 using randomly generated numbers in the range (-10,10). <font color=red>[7 points]</font>
2. Create the four array slices shown in the figure below and marked by the four different __colors__  (Red,Green,Orange,Blue), i.e. each color is a separate slice. <font color=red> [7 points for each correct slice] </font>
<img src="Ex1-Slices.png" width="150">
    
3. Create a boolean mask to identify the locations of all negative numbers in the array `X` above <font color=red>[5 points for crorrect mask]</font>, and then
    * use the mask (or the locations) to display those negative numbers <font color=red>[5 points ]</font>. 
    * use the mask (or the locations) to change all those negative numbers to 0's <font color=red>[5 points]</font>. 


--------

## <font color=Green> Answers: </font>

- <font color=red> Note: </font> a sample output is given below, your output numbers could be different due to the random generation of the array. 

In [17]:
import random 
import numpy as np
from array import *

#### <font color=Green> 1 - array creation [7 points]

In [109]:
X=np.random.randint(-10,10,(8,6))
print(X)

[[  7   0  -7   2   2  -3]
 [ -1   6 -10   4   2  -2]
 [ -2  -5   0 -10  -8  -1]
 [  8 -10  -2  -4  -1  -6]
 [ -9   2   4  -6   7   8]
 [ -8   5   8  -4 -10  -8]
 [  3   3   0   4  -2  -3]
 [ -4   9  -2   0   8   5]]


In [39]:
#Sample output of randomly generated 8x6 array

Based on the generated array above, the slices will be as follows:
<img src="Ex1-Slices-numArray.png" width="250">

#### <font color=Green> 2- Slicing the array X


- __2.1 - The Orange slice__  [7 points]

In [110]:
# Sample output of the Orange slice from the array X above
X[6:, 2:4 ]


array([[ 0,  4],
       [-2,  0]])

- __2.2 - The Green slice__ [7 points]

In [111]:
# Sample output of the Green slice from the array X above
np.diag(X[1:7])
 

array([ -1,  -5,  -2,  -6, -10,  -3])

- __2.3 - The Blue slice__ [7 points]

In [112]:
# Sample output of the Blue slice from the array X above
X[:1, ::2 ]

array([[ 7, -7,  2]])

- __2.4 - The Red slice__ [7 points]

In [113]:
# Sample output of the Red slice from the array X above
np.fliplr(X[1:7]).diagonal()

array([-2, -8, -4,  4,  5,  3])

#### <font color=Green> 3- Boolean mask to identify the locations of all negative (-ve) numbers in the array

- __3.1 The mask__ [5 points]

In [125]:

m = np.where(X<0,True,False )
#print(X)
print(m)

[[False False  True False False  True]
 [ True False  True False False  True]
 [ True  True False  True  True  True]
 [False  True  True  True  True  True]
 [ True False False  True False False]
 [ True False False  True  True  True]
 [False False False False  True  True]
 [ True False  True False False False]]


* Note: 
* The mask's shape is the same as the array used to create it (X)'s shape. 
* The first value in the mask (at [0,0]) is `True` which means the first number in array X is negative. This is the case for all X values that correspond to `True` values in the mask. 
* When we apply the mask, only the X values that correspond to `True` will be selected.

* Also the Mask can be represented as indexes of the -ve numbers. The index has two arrays
     - The first array for rows indexes 
     - the 2nd array for columns indexes


In [124]:
i = np.where(X<0)
# Sample output for the mask indexes
print(i)

(array([0, 0, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 5, 5, 5, 5, 6,
       6, 7, 7], dtype=int64), array([2, 5, 0, 2, 5, 0, 1, 3, 4, 5, 1, 2, 3, 4, 5, 0, 3, 0, 3, 4, 5, 4,
       5, 0, 2], dtype=int64))


 -  for instance, in the indexes above, the index `[0,0]` is the row and column index of the 1st negative number, and `[7,4]` is the index of the last -ve number in the array. So we can list the -ve numbers using the mask or its corresponding index format 

- __3.2 Use the mask to display the -ve numbers__ [5 points]

In [126]:
# Sample output for the -ve numbers in the array displayed using the mask (or the mask indexes) above
i = np.where(X<0)
#print(X)
print(X[i])

[ -7  -3  -1 -10  -2  -2  -5 -10  -8  -1 -10  -2  -4  -1  -6  -9  -6  -8
  -4 -10  -8  -2  -3  -4  -2]


- __3.3 Use the mask to change the -ve numbers in X to 0's__ [5 points]

In [127]:
# Sample output for the array after -ve values were changed to 0's
np.where(X<0,0,X )
#print(X)

array([[7, 0, 0, 2, 2, 0],
       [0, 6, 0, 4, 2, 0],
       [0, 0, 0, 0, 0, 0],
       [8, 0, 0, 0, 0, 0],
       [0, 2, 4, 0, 7, 8],
       [0, 5, 8, 0, 0, 0],
       [3, 3, 0, 4, 0, 0],
       [0, 9, 0, 0, 8, 5]])